@startuml
!include ../../../images/common-sequence.iuml

title delete-func-api-firmware-delete\n(GitHub Action → CloudFormation)

actor "GitHub Actions Runner" as GHA

box "AWS" #ffdbbb
    participant "CloudFormation / SAM" as CF
    participant "API Gateway" as APIGW
end box

GHA -> CF++ : SAM delete\nstack: firefly-func-api-firmware-delete
CF -> APIGW : Remove route\nDELETE /firmware/{zip_name}
CF --> GHA-- : DELETE_COMPLETE

@enduml
