@startuml
!include ../../../../images/common-sequence.iuml

title MQTT — Connection & Availability

box "On-Premises" $OnPrem
    participant "Controller" as ctl
    participant "MQTT Broker" as mqtt
    participant "Home Assistant" as ha
end box

ha -> mqtt : **Subscribe**\nhomeassistant/#

ctl -> mqtt : **Connect** (Last Will) QoS 2, retained\nFireFly/{UUID}/availability\n""offline""

ctl -> mqtt : **Publish availability online**\nFireFly/{UUID}/availability\n""online""\nretained
mqtt -> ha : **Publish availability online**\nFireFly/{UUID}/availability\n""online""\nretained
ha -> ha : **Set all entities available**

opt Network / MQTT Connection Failure
    mqtt -x ctl : **Heartbeat connection request**
    mqtt -> mqtt : **Connection lost**
    mqtt -> ha : **Publish Last Will and Testament**\nFireFly/{UUID}/availability\n""offline""\nretained
    ha -> ha : **Set all entities unavailable**\n""Unavailable""
end

@enduml
