@startuml
!include ../../../../images/common-sequence.iuml

title MQTT — Connection & Availability

box "On-Premises" $OnPrem
    participant "Client" as client
    participant "MQTT Broker" as mqtt
    participant "Home Assistant" as ha
end box

ha -> mqtt : **Subscribe**\nhomeassistant/#

client -> mqtt : **Connect to MQTT and set Last Will**\nFireFly/{UUID}/availability\n""offline""\nQoS 0\nretained

client -> mqtt : **Publish availability online**\nFireFly/{UUID}/availability\n""online""\nretained
mqtt -> ha : **Publish availability online**\nFireFly/{UUID}/availability\n""online""\nretained
ha -> ha : **Set all entities available**

opt Network / MQTT Connection Failure
    mqtt -x client : **Heartbeat connection request**
    mqtt -> mqtt : **Connection lost**
    mqtt -> ha : **Publish Last Will and Testament**\nFireFly/{UUID}/availability\n""offline""\nretained
    ha -> ha : **Set all entities unavailable**\n""Unavailable""
end

@enduml
