@startuml
!include ../../../images/common-sequence.iuml

title GET /health

actor Client

box "AWS" #ffdbbb
    participant "API Gateway" as APIGW
    participant "func-api-health" as Lambda
end box

Client -> APIGW++ : GET /health
APIGW -> Lambda++ : invoke
Lambda --> APIGW-- : 200 OK\n{"status": "OK"}
APIGW --> Client-- : 200 OK\n{"status": "OK"}

@enduml
